#+title: TCP
#+setupfile: ../../../clean.theme
* TCP                                                                   :tcp:
:PROPERTIES:
:ID:       a2c33f5d-8e07-4122-98df-72d321ae313b
:CREATED:  <2025-01-18 Sat 20:42>
:END:
:EDGES:
[2025-03-03 Mon 15:39] -- [[https://www.ietf.org/rfc/rfc793.html][RFC793]]
[2025-03-03 Mon 15:47] >> [[id:2c915d42-3f42-4a94-a2d7-af73c9938c7b][IP]]
:END:
- [[https://blog.cloudflare.com/when-tcp-sockets-refuse-to-die/][When TCP sockets refuse to die]]
  - [[https://lisperator.net/blog/common-lisp-socket-client---reconnect-on-failure/][Common Lisp socket client - reconnect on failure]]
** WebSocket
:PROPERTIES:
:ID:       52a7cb9d-5b78-4681-9146-2d8f5707c1a3
:CREATED:  <2025-02-16 Sun 20:41>
:END:
:EDGES:
[2025-03-03 Mon 15:40] -- [[https://datatracker.ietf.org/doc/html/rfc6455][RFC 6455 - The WebSocket Protocol]]
[2025-03-03 Mon 15:46] <- [[id:989ae244-f798-425c-bcf1-32014eafbd22][WebRTC]]
:END:
- layer on top of TCP
- [[https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API][The WebSocket API (WebSockets) - Web APIs | MDN]]
** HTTP                                                                :http:
:PROPERTIES:
:ID:       5c9b8b56-6c37-4171-8da1-ac6e4e3cd0a1
:CREATED:  <2025-01-18 Sat 20:42>
:END:
:EDGES:
[2025-03-03 Mon 15:40] -- [[https://developer.mozilla.org/en-US/docs/Web/HTTP][HTTP | MDN]]
[2025-09-30 Tue 15:51] -- [[https://http.dev/][HyperText Transfer Protocol (HTTP) explained]]
:END:
#+begin_quote
Hypertext Transfer Protocol (HTTP) is an application-layer protocol
for transmitting hypermedia documents, such as HTML. It was designed
for communication between web browsers and web servers, but it can
also be used for other purposes. HTTP follows a classical
client-server model, with a client opening a connection to make a
request, then waiting until it receives a response. HTTP is a
stateless protocol, meaning that the server does not keep any data
(state) between two requests. Though often based on a TCP/IP layer, it
can be used on any reliable transport layer, that is, a protocol that
doesn't lose messages silently like UDP does. RUDP - the reliable
update of UDP - is a suitable alternative.
#+end_quote
#+begin_center
-- [[https://developer.mozilla.org/en-US/docs/Web/HTTP][MDN web docs]]
#+end_center
- [[https://http.dev/1.0][HTTP/1.0 explained]]
*** HTTP/1.1
:PROPERTIES:
:ID:       95274690-c607-4c94-9416-707f478814ae
:CREATED:  <2025-09-30 Tue 15:40>
:END:
:EDGES:
[2025-09-30 Tue 15:41] -- [[https://http.dev/1.1][HTTP/1.1 explained]]
:END:
*** HTTP/2
:PROPERTIES:
:ID:       2d727cb5-b30c-47f8-b208-eccd1d32d40d
:CREATED:  <2025-09-30 Tue 15:40>
:END:
:EDGES:
[2025-09-30 Tue 15:41] -- [[https://http.dev/2][HTTP/2 explained]]
:END:
*** HTTPS                                                               :tls:
:PROPERTIES:
:ID:       81e78198-a5ed-4fdd-b487-1bb3874ffa71
:CREATED:  <2025-02-16 Sun 20:40>
:END:
:EDGES:
[2025-03-03 Mon 15:41] -- [[https://https.cio.gov/][The HTTPS-Only Standard - The HTTPS-Only Standard]]
[2025-03-03 Mon 15:41] -- [[https://developer.mozilla.org/en-US/docs/Glossary/HTTPS][HTTPS - MDN Web Docs Glossary: Definitions of Web-related terms | MDN]]
[2025-03-03 Mon 15:46] << [[id:031f06eb-b4a6-4386-a17f-33712bf67181][QUIC]]
:END:
- HTTPS consists of HTTP with the addition of [[file:../../../../Z/core/notes/tls.org][TLS]]
- HTTP/S is used as a blanket statement for both HTTP and HTTPS
*** REST
:PROPERTIES:
:ID:       c0cc13d2-f8c2-4772-9a1e-86e406e118bf
:CREATED:  <2025-09-29 Mon 19:40>
:END:
:EDGES:
[2025-09-29 Mon 19:40] -- [[https://restfulapi.net/][What is REST?: REST API Tutorial]]
:END:
*** GraphQL
:PROPERTIES:
:ID:       3cf5d8cb-c70b-4ba3-a166-d69e740a5505
:CREATED:  <2025-09-29 Mon 19:40>
:END:
:EDGES:
[2025-09-29 Mon 19:40] -- [[https://graphql.org/][GraphQL | A query language for your API]]
:END:
** DICT
:PROPERTIES:
:ID:       407f25fd-aab0-4aa5-a994-abb1be11fae5
:CREATED:  <2025-10-11 Sat 22:30>
:AKA: Dictionary Server Protocol
:END:
:EDGES:
[2025-10-11 Sat 22:30] -- [[man:dictd][man]]
[2025-10-11 Sat 22:32] -- [[archwiki:Dictd][archwiki]]
:END:
Query/Response protocol which allows a client to access dictionary
definitions from a set of natural language dictionary databases.

#+begin_quote
For many years, the Internet community has relied on the "webster"
protocol for access to natural language definitions. The webster
protocol supports access to a single dictionary and (optionally) to a
single thesaurus. In recent years, the number of publicly available
webster servers on the Internet has dramatically decreased.

Fortunately, several freely-distributable dictionaries and lexicons
have recently become available on the Internet. However, these
freely-distributable databases are not accessible via a uniform
interface, and are not accessible from a single site. They are often
small and incomplete individually, but would collectively provide an
interesting and useful database of English words. Examples include the
Jargon file, the WordNet database, MICRA's version of the 1913
Webster's Revised Unabridged Dictionary, and the Free Online
Dictionary of Computing. (See the DICT protocol specification (RFC)
for references.) Translating and non-English dictionaries are also
becoming available (for example, the FOLDOC dictionary is being
translated into Spanish).

The webster protocol is not suitable for providing access to a large
number of separate dictionary databases, and extensions to the current
webster protocol were not felt to be a clean solution to the
dictionary database problem.

The DICT protocol is designed to provide access to multiple
databases. Word definitions can be requested, the word index can be
searched (using an easily extended set of algorithms), information
about the server can be provided (e.g., which index search strategies
are supported, or which databases are available), and information
about a database can be provided (e.g., copyright, citation, or
distribution information). Further, the DICT protocol has hooks that
can be used to restrict access to some or all of the databases.
#+end_quote
