#+title: GNU Software
#+setupfile: ../../clean.theme
* Emacs                                                               :emacs:
:PROPERTIES:
:ID:       5fc53135-1b6c-4260-b264-66be7a2b8ff0
:CREATED:  <2025-01-18 Sat 20:47>
:END:
:EDGES:
[2025-02-13 Thu 22:39] -- [[https://www.gnu.org/software/emacs/][GNU Emacs]]
[2025-02-13 Thu 22:41] -- [[https://www.gnu.org/software/emacs/manual/][Online Manuals]]
[2025-03-03 Mon 14:01] << [[id:6c69c42b-3d0a-48bf-a5ad-43b350477387][Elisp]]
[2025-03-03 Mon 16:27] -- [[man:emacs][man]]
[2025-05-10 Sat 23:10] >> [[id:eddaae08-a0c1-4413-9f0a-804f663ae176][IDE]]
:END:
- refer to the INSTALL file in the root of the emacs repo for an
  overview of install options
- releases are hosted at [[https://ftp.gnu.org/gnu/emacs/]]
** Releases
:PROPERTIES:
:CUSTOM_ID: releases
:ID:       cfe9d1b9-f6f4-4866-8291-d125fc8b3eb6
:END:
   For sanity checking, it's helpful to have access to older versions
   of Emacs. We can download and verify a version like this:
   #+begin_src shell :results silent
#aria2c https://ftp.gnu.org/gnu/gnu-keyring.gpg -d /tmp/
#gpg --import /tmp/gnu-keyring.gpg
VERSION=24.2
aria2c https://ftp.gnu.org/gnu/emacs/emacs-${VERSION}.tar.xz.sig -d /tmp/
gpg --verify /tmp/emacs-${VERSION}.tar.xz.sig
aria2c https://ftp.gnu.org/gnu/emacs/emacs-${VERSION}.tar.xz -d /tmp/
tar -xf emacs-${VERSION}.tar.xz
   #+end_src

** Building from Source
:PROPERTIES:
:CUSTOM_ID: building_from_source
:ID:       31710a0d-bd27-4549-894e-62bb8ceaa015
:END:

   First, clone the repo:
     #+begin_src shell :results silent
git clone https://git.savannah.gnu.org/git/emacs.git /tmp/emacs
     #+end_src

   Once the source is in hand, I strongly recommend making a separate
   build directory and calling the configure script from there.

   #+begin_src shell
mkdir /tmp/emacs-build && cd /tmp/emacs-build
../emacs/configure --with-mailutils --with-imagemagick --with-x-toolkit=athena --without-pop --without-sound --with-json --enable-link-time-optimization --with-native-compilation --with-modules
NATIVE_FULL_AOT=1 make -j8
# test the build with './src/emacs' (location of output binary)
# install emacs binaries on current system
make install
   #+end_src

   The =configure= script takes a bunch of different flags that
   customize the build, and generate a build-specific Makefile.

   The next line compiles the source. Install with =make install= and
   you're done! A custom Emacs binary with all the fixings has just
   been installed for your current user. :)

   Here are some of the other configuration flags worth investigating:

   - --without-all
   - --with-x-toolkit=no
   - --without-x
   - --without-dbus --without-gconf --without-gsettings

** Eww                                                              :browser:
:PROPERTIES:
:ID:       21adcc1c-67ee-4f50-9049-12794824b2c7
:CREATED:  <2025-03-01 Sat 13:35>
:END:
:EDGES:
[2025-03-01 Sat 13:36] -- [[https://www.emacswiki.org/emacs/eww][EmacsWiki: eww]]
:END:
the Emacs Web Wowser, a browser written in elisp based on shr.el.
#+begin_src shell :exports code :results none
  eww() {
   emacsclient -a '' -t -e '(eww-browse-url "'"$1"'")'
  }
#+end_src

** Speedbar
:PROPERTIES:
:ID:       2cebd8b2-615e-44b2-afd4-2e302f836dd3
:CREATED:  <2025-03-03 Mon 13:43>
:END:
:EDGES:
[2025-03-03 Mon 13:44] -- [[info:speedbar][info]]
:END:

** ERC                                                                  :irc:
:PROPERTIES:
:ID:       a42c2aaa-8dda-40ca-b455-7511f0cb084a
:CREATED:  <2025-03-03 Mon 16:45>
:END:
:EDGES:
[2025-03-03 Mon 16:46] -- [[info:erc][info]]
[2026-05-08 Fri 19:50] >> [[id:13368ff1-b66a-4f98-beba-bb7687d963f4][IRC]]
:END:

** EUDC
:PROPERTIES:
:ID:       b72f96f7-4040-4548-8da2-e619d26c4887
:CREATED:  <2025-03-03 Mon 16:47>
:END:
:EDGES:
[2025-03-03 Mon 16:48] -- [[info:eudc][info]]
:END:
Emacs Unified Directory Client
*** BBDB                                                               :bbdb:
:PROPERTIES:
:ID:       db8e43f4-78ec-4fb1-93e7-11ac7ee87799
:CREATED:  <2025-03-03 Mon 17:46>
:END:
:EDGES:
[2025-03-03 Mon 17:46] -- [[info:eudc#bbdb][info]]
[2025-03-03 Mon 20:19] -- [[https://savannah.nongnu.org/projects/bbdb/][Insidious Big Brother Database - Summary [Savannah]​]]
:END:

** SLIME                                                            :lisp:cl:
:PROPERTIES:
:ID:       f499c680-9a01-4a11-bc69-81861fd864d0
:CREATED:  <2025-03-03 Mon 17:45>
:END:
:EDGES:
[2025-03-03 Mon 17:46] -- [[info:slime][info]]
[2026-05-08 Fri 19:55] <- [[id:a69e0d55-e25f-4332-8fdc-aad2843ba649][Swank]]
:END:

** Eshell
:PROPERTIES:
:ID:       86dbf792-301b-405e-806b-3df7e9531279
:CREATED:  <2025-03-03 Mon 19:57>
:END:
:EDGES:
[2025-03-03 Mon 19:57] -- [[info:eshell][info]]
[2025-03-04 Tue 15:49] -- [[https://www.masteringemacs.org/article/complete-guide-mastering-eshell][Mastering Eshell - Mastering Emacs]]
[2025-03-04 Tue 15:50] -- [[https://github.com/howardabrams/dot-files/blob/master/emacs-eshell.org][howardabrams/dot-files/emacs-eshell.org]]
[2025-03-04 Tue 15:50] -- [[https://howardism.org/Technical/Emacs/eshell-why.html][Why use EShell?]]
[2025-03-04 Tue 15:51] -- [[https://www.emacswiki.org/emacs/CategoryEshell][EmacsWiki: Category Eshell]]
[2025-03-04 Tue 15:51] -- [[https://www.gonsie.com/blorg/eshell.html][Don't be afraid of eshell]]
:END:
** Eglot
:PROPERTIES:
:ID:       8b1452eb-fc57-4026-8587-91ff8ebccba6
:CREATED:  <2025-03-03 Mon 19:57>
:END:
:EDGES:
[2025-03-03 Mon 19:57] -- [[info:eglot][info]]
:END:
#+begin_quote
Eglot is the Emacs client for the “Language Server Protocol” (LSP).  The
name "Eglot" is an acronym that stands for "Emacs polyGLOT". (1) Eglot
provides infrastructure and a set of commands for enriching the source
code editing capabilities of Emacs via LSP.  LSP is a standardized
communications protocol between source code editors (such as Emacs) and
language servers--programs external to Emacs which analyze the source
code on behalf of Emacs.  The protocol allows Emacs to receive various
source code services from the server, such as description and location
of function calls, types of variables, class definitions, syntactic
errors, etc.  This way, Emacs doesn't need to implement the
language-specific parsing and analysis capabilities in its own code, but
is still capable of providing sophisticated editing features that rely
on such capabilities, such as automatic code completion, go-to
definition of function/class, documentation of symbol at-point,
refactoring, on-the-fly diagnostics, and more.

   Eglot itself is completely language-agnostic, but it can support any
programming language for which there is a language server and an Emacs
major mode.
#+end_quote
- [[help:eglot-server-programs][eglot-server-programs]]
  - alist of ~(major-mode . server)~
- [[info:eglot#Advanced server configuration][eglot#Advanced server configuration]]

- Featues
  #+begin_quote
   • At-point documentation: when point is near a symbol or an
     identifier, information about the identifier's significance in the
     program (its function or method signature, its type, its custom
     documentation string, etc.)  is made available via the ElDoc
     package (*note (emacs)Programming Language Doc::).

   • On-the-fly diagnostic annotations, via the Flymake package (*note
     (Flymake)Top::).  Eglot's Flymake backend replaces other Flymake
     backends while it is managing a buffer, and enhances diagnostics
     with interactive server-suggested fixes (so-called “code actions”,
     *note Eglot Commands::).

   • Finding definitions and uses of identifiers, via Xref (*note
     (emacs)Xref::).  Eglot provides a backend for the Xref capabilities
     which uses the language server's understanding of the program
     source.  In particular, it eliminates the need to generate tags
     tables (*note (emacs)Tags tables::) for languages which are only
     supported by the ‘etags’ backend.

   • Buffer navigation by name of function, class, method, etc., via
     Imenu (*note (emacs)Imenu::).  Eglot provides its own variant of
     ‘imenu-create-index-function’, which generates the index for the
     buffer based on the language server's program source analysis.

   • Enhanced completion of symbol at point by the ‘completion-at-point’
     command (*note (emacs)Symbol Completion::).  This uses the language
     server's parser data for the completion candidates.

   • Server-suggested code refactorings.  The ElDoc package is also
     leveraged to retrieve so-called “code actions” nearby point.  When
     such suggestions are available they are annotated with a special
     indication and can be easily invoked by the user with the
     ‘eglot-code-action’ command (*note Eglot Commands::).

   • On-the-fly succinct informative annotations, so-called “inlay
     hints”.  Eglot adds special intangible text nearby certain
     identifiers, be it the type of a variable, or the name of a formal
     parameter in a function call.  *Note Eglot Commands::, and the
     ‘eglot-inlay-hints-mode’ minor mode.

   • Enhanced source code fontification via LSP “semantic tokens”.
     Eglot can leverage the language server's understanding of the role
     and meaning of identifiers in the code to provide more accurate
     syntax highlighting.  *Note Eglot Commands::, and the
     ‘eglot-semantic-tokens-mode’ minor mode.

   • Display of function call and type hierarchies via the
     ‘eglot-show-call-hierarchy’ and ‘eglot-show-type-hierarchy’
     commands (*note Eglot Commands::).

   • Code reformatting via the ‘eglot-format’ and related commands
     (*note Eglot Commands::).  Automatic reformatting of source code is
     also supported and is activated automatically as you type.

   • Eglot enhances symbol completion front-ends by providing completion
     candidates based on the language server's understanding of the
     source code (*note (emacs)Symbol Completion::).  The Company
     package, installable from GNU ELPA, is a popular package known to
     work well with Eglot.

   • If YASnippet, a popular third-party package for automatic insertion
     of code templates (snippets), is installed, and the language server
     supports snippet completion candidates, Eglot arranges for the
     completion package to instantiate these snippets using YASnippet.
     (YASnippet can be installed from GNU ELPA.)

   • When the server provides at-point documentation formatted as
     Markdown in addition to plain text, Eglot arranges for the ElDoc
     package to enrich this text with fontifications, hyperlinks and
     other nice formatting before displaying it to the user.  This makes
     the documentation shown by ElDoc look nicer on display.

   • In addition to enabling and enhancing other features and packages,
     Eglot also provides a number of user commands based on the
     capabilities of language servers.  Examples include renaming
     symbols with ‘eglot-rename’ and asking to automatically correct
     problems with ‘eglot-code-actions’.  *Note Eglot Commands::.
  #+end_quote
- eglot is /optimistic/ by default - to opt out of features use
  =eglot-ignored-server-capabilities= and =eglot-managed-mode-hook=

- autostart: =(add-hook 'foo-mode-hook 'eglot-ensure)=
  - on first connection: =eglot-connect-hook=

- some multiserver scenarios not supported by Eglot's architecture,
  better off building a LSP server multiplexer (hint hint)
  - [[https://github.com/joaotavora/rassumfrassum][joaotavora/rassumfrassum]]

- extension documentation recommends just read the source
  - uses generics
  - example included: [[info:eglot#Extending Eglot][eglot#Extending Eglot]] : inactiveRegions clangd
    17 feature
  - see also [[info:eglot#JSONRPC objects in Elisp][eglot#JSONRPC objects in Elisp]]

- performance opts: =eglot-events-buffer-config=
** Calc
:PROPERTIES:
:ID:       92ad7518-cf81-4aca-9940-bd40fb02f5dd
:CREATED:  <2025-06-09 Mon 17:00>
:END:
:EDGES:
[2025-06-09 Mon 17:00] -- [[info:calc][info]]
[2025-06-09 Mon 17:00] -> [[id:5b37c685-ab0a-4d3b-b278-c99f90292fcb][CAS]]
[2025-06-09 Mon 17:02] -- [[https://www.emacswiki.org/emacs/Calc][EmacsWiki: Calc]]
[2025-06-09 Mon 17:02] -- [[https://www.masteringemacs.org/article/fun-emacs-calc][Fun with Emacs Calc - Mastering Emacs]]
[2025-06-09 Mon 17:03] -- [[https://www.gnu.org/software/emacs/refcards/pdf/calccard.pdf][calc cheatsheet]]
:END:
#+begin_src calc
  24
  3
  '/
#+end_src

#+RESULTS:
: 8

#+begin_src calc
  fsolve(x*2+x=4,x)
#+end_src

#+RESULTS:
: x = 1.33333333333

#+begin_src calc
  fsolve([x + y = a, x - y = b],[x,y])
#+end_src

#+RESULTS:
: [x = a + (b - a) / 2, y = (a - b) / 2]

** dictionary
:PROPERTIES:
:ID:       c344fc40-d6d8-4553-885b-fe8c55d6aa98
:CREATED:  <2025-10-11 Sat 22:36>
:END:
- see also [[https://www.masteringemacs.org/article/wordsmithing-in-emacs][Wordsmithing in Emacs - Mastering Emacs]]
** SES
:PROPERTIES:
:ID:       c40383a3-c717-43c6-8188-e2a564a641a1
:CREATED:  <2025-03-03 Mon 19:58>
:END:
:EDGES:
[2025-03-03 Mon 19:58] -- [[info:ses][info]]
:END:
Simple Emacs Spreadsheet

** Packages
:PROPERTIES:
:ID:       8b2930be-e877-4e6b-aea4-372be3c8340c
:CREATED:  <2025-03-09 Sun 19:05>
:END:
*** Org-roam                                                            :org:
:PROPERTIES:
:ID:       3bb08e71-1ce9-46ed-844a-31305162645e
:CREATED:  <2025-03-03 Mon 19:46>
:END:
:EDGES:
[2025-03-03 Mon 19:46] -- [[https://www.orgroam.com/][Org-roam]]
[2025-03-03 Mon 19:47] -> [[id:8889ae64-a982-4f6c-a875-5cbae6dbb323][Knowledge System]]
:END:
#+begin_quote
A plain-text personal knowledge management system.
#+end_quote
- Popular extension which uses a sqlite backend to persist a Roam-like
  graph of Org-mode nodes.
- Our own =graph.el= implementation in core/emacs is inspired by
  org-roam
*** emacs-scrum                                                         :org:
:PROPERTIES:
:ID:       947597c2-8f17-4ba8-8af7-6d5784219b0c
:CREATED:  <2025-03-15 Sat 16:56>
:END:
:EDGES:
[2025-03-15 Sat 16:58] -- [[https://github.com/ianxm/emacs-scrum][src]]
:END:
#+begin_quote
dynamic scrum report generation for org-mode buffers
#+end_quote
*** vertico
:PROPERTIES:
:ID:       b1c1d365-1983-4e63-8cf6-c032932ff1b9
:CREATED:  <2025-06-09 Mon 17:08>
:END:
:EDGES:
[2025-06-09 Mon 17:09] -- [[https://github.com/minad/vertico][src]]
:END:
*** corfu
:PROPERTIES:
:ID:       371ff3e8-d0e0-4260-bc41-4ba53d635ce5
:CREATED:  <2025-06-09 Mon 17:09>
:END:
:EDGES:
[2025-06-09 Mon 17:10] -- [[https://github.com/minad/corfu][src]]
:END:
Completion in Region Function
*** cape
:PROPERTIES:
:ID:       c69f7d77-7ec1-4d7e-b70d-23e54cdced4b
:CREATED:  <2025-06-09 Mon 17:10>
:END:
:EDGES:
[2025-06-09 Mon 17:10] -- [[https://github.com/minad/cape][src]]
:END:

*** kanban.el                                                           :org:
:PROPERTIES:
:ID:       5ff7407e-32a0-463b-bf59-9519875da655
:CREATED:  <2025-03-15 Sat 16:57>
:END:
:EDGES:
[2025-03-15 Sat 16:57] -- [[https://www.draketo.de/files/kanban.el][src]]
:END:
#+begin_quote
Parse org-todo headlines to use org-tables as Kanban tables
#+end_quote
** Apps
:PROPERTIES:
:ID:       1bbc8529-d207-4a7e-a72a-b231316c90e6
:CREATED:  <2025-03-03 Mon 15:54>
:END:
*** Cloudmacs
:PROPERTIES:
:ID:       defa663e-3522-475c-ad44-615b64edabf1
:CREATED:  <2025-03-03 Mon 15:54>
:END:
:EDGES:
[2025-03-03 Mon 13:44] -- [[https://beepb00p.xyz/cloudmacs.html][Cloudmacs: Emacs in your web browser | beepb00p]]
:END:
** Blogs
:PROPERTIES:
:ID:       4d72736e-f3c1-4b6f-839d-474710771d78
:CREATED:  <2025-10-11 Sat 22:33>
:END:
*** Mastering Emacs
:PROPERTIES:
:ID:       cf98496a-d864-4878-8401-ffaa73aa7d04
:CREATED:  <2025-10-11 Sat 22:33>
:END:
:EDGES:
[2025-10-11 Sat 22:34] -- [[https://www.masteringemacs.org/][Mastering Emacs]]
:END:
*** Sacha Chua
:PROPERTIES:
:ID:       c6d79f1d-e5bd-479e-82fa-20df7e5dd83f
:CREATED:  <2025-10-11 Sat 22:34>
:END:
:EDGES:
[2025-10-11 Sat 22:34] -- [[https://sachachua.com/][Home :: Sacha Chua]]
:END:
* GNU Radio
:PROPERTIES:
:ID:       c92b3830-3836-41b0-a502-f04b44cd3292
:CREATED:  <2025-02-14 Fri 22:22>
:END:
:EDGES:
[2025-02-14 Fri 22:23] -- [[https://www.gnuradio.org/][GNU Radio]]
[2025-02-14 Fri 22:23] -- [[https://wiki.gnuradio.org/index.php?title=What_Is_GNU_Radio][What Is GNU Radio - GNU Radio]]
:END:
** GRC                                                                  :gui:
:PROPERTIES:
:ID:       c272a3f2-b0b0-4784-aeaf-4c677cbbd708
:CREATED:  <2025-03-03 Mon 16:32>
:END:
:EDGES:
[2025-03-03 Mon 16:32] -- [[man:gnuradio-companion][man]]
:END:
GNU Radio Companion
- GUI tool for creating signal flowgraphs
* Stow
:PROPERTIES:
:ID:       0b60eedf-686b-4f9a-bc2b-7cee2be7e828
:CREATED:  <2026-04-18 Sat 20:46>
:END:
:EDGES:
[2026-04-18 Sat 20:46] -- [[https://www.gnu.org/software/stow/][Stow - GNU Project - Free Software Foundation]]
:END:
#+begin_quote
GNU Stow is a symlink farm manager which takes distinct packages of
software and/or data located in separate directories on the
filesystem, and makes them appear to be installed in the same
place. For example, =/usr/local/bin= could contain symlinks to files
within =/usr/local/stow/emacs/bin=, =/usr/local/stow/perl/bin= etc., and
likewise recursively for any other subdirectories such as ~.../share~,
~.../man~, and so on.
#+end_quote
