#+title: QEMU
#+setupfile: ../../clean.theme
#+filetags: virt
* QEMU
:PROPERTIES:
:ID:       c4f26ef4-a936-4cf3-8218-4d23dbd9b33a
:CREATED:  <2025-09-19 Fri 18:56>
:END:
:EDGES:
[2025-09-19 Fri 18:56] -- [[man:qemu][man]]
[2025-09-19 Fri 18:57] -- [[https://www.qemu.org/docs/master/index.html][docs]]
:END:
#+begin_quote
QEMU is a generic and open source machine emulator and virtualizer.

QEMU can be used in several different ways. The most common is for
System Emulation, where it provides a virtual model of an entire
machine (CPU, memory and emulated devices) to run a guest OS. In this
mode the CPU may be fully emulated, or it may work with a hypervisor
such as KVM, Xen or Hypervisor.Framework to allow the guest to run
directly on the host CPU.

The second supported way to use QEMU is User Mode Emulation, where
QEMU can launch processes compiled for one CPU on another CPU. In this
mode the CPU is always emulated.

QEMU also provides a number of standalone command line utilities, such
as the qemu-img disk image utility that allows you to create, convert
and modify disk images.
#+end_quote

- [[https://www.qemu.org/docs/master/tools/index.html][Tools - QEMU documentation]]

#+begin_example
$ qemu-system-x86_64 [machine opts] \
                [cpu opts] \
                [accelerator opts] \
                [device opts] \
                [backend opts] \
                [interface opts] \
                [boot opts]
#+end_example

** chroot archlinux-bootstrap
:PROPERTIES:
:ID:       c2b1211c-870c-451d-b0fa-f9cce4f6a0a7
:END:
#+begin_src bash :dir /sudo::
  src=http://mirrors.mit.edu/archlinux/iso/latest/archlinux-bootstrap-x86_64.tar.gz
  archive=/tmp/archlinux-bootstrap-x86_64.tar.gz
  image=/tmp/image.raw
  mountpoint=/tmp/arch
  if [[ ! -f $archive ]]; then
      wget $src -O $archive
  fi
  mkdir $mountpoint
  qemu-img create -f raw $image 20G
  loop=$(sudo losetup --show -f -P $image)
  sudo parted $loop mklabel msdos
  sudo parted -a optimal $loop mkpart primary 0% 100%
  sudo parted $loop set 1 boot on
  loopp=${loop}p1
  sudo mkfs.ext4 $loopp
  sudo mount $loopp $mountpoint
  sudo tar xf $archive -C $mountpoint --strip-components 1

  sudo $mountpoint/bin/arch-chroot $mountpoint /bin/bash <<EOL
  set -v

  echo 'Server = http://ftp.uni-bayreuth.de/linux/archlinux/\$repo/os/\$arch' >> /etc/pacman.d/mirrorlist

  pacman-key --init
  pacman-key --populate archlinux

  pacman -Syu --noconfirm
  pacman -S --noconfirm base linux linux-firmware mkinitcpio dhcpcd syslinux
  systemctl enable dhcpcd

  # Standard Archlinux Setup
  ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime
  hwclock --systohc
  echo en_US.UTF-8 UTF-8 >> /etc/locale.gen
  locale-gen
  echo LANG=en_US.UTF-8 > /etc/locale.conf
  echo arch-qemu > /etc/hostname
  echo -e '127.0.0.1  localhost\n::1  localhost' >> /etc/hosts

  # Create an initramfs without autodetect, because this breaks with the
  # combination host/chroot/qemu
  linux_version=\$(ls /lib/modules/ | sort -V | tail -n 1)
  mkinitcpio -c /etc/mkinitcpio.conf -S autodetect --kernel \$linux_version -g /boot/initramfs-linux-custom.img

  # Setup syslinux
  mkdir /boot/syslinux
  cp /usr/lib/syslinux/bios/*.c32 /boot/syslinux/
  extlinux --install --device $loopp /boot/syslinux
  dd bs=440 count=1 conv=notrunc if=/usr/lib/syslinux/bios/mbr.bin of=$loop
  # Customize syslinux config
  uuid=\$(blkid -o value -s UUID $loopp)
  sed -i '1i SERIAL 0 115200' /boot/syslinux/syslinux.cfg
  sed -i "s/APPEND root=\/dev\/sda3/APPEND console=tty0 console=ttyS0,115200 root=UUID=\$uuid/g" /boot/syslinux/syslinux.cfg
  sed -i "s/INITRD ..\/initramfs-linux.img/INITRD ..\/initramfs-linux-custom.img/" /boot/syslinux/syslinux.cfg
  EOL

  sudo umount $mountpoint
  sudo losetup -d $loop
#+end_src

#+RESULTS:
| Formatting '/tmp/image.raw' | fmt=raw size=21474836480 |
