#+title: LSP
#+setupfile: ../../clean.theme
* Language Server Protocol
:PROPERTIES:
:ID:       51bd814a-a93d-42e9-9a74-06a463be85f5
:CREATED:  <2026-05-22 Fri 22:12>
:AKA: LSP
:END:
:EDGES:
[2026-05-22 Fri 22:13] -- [[https://microsoft.github.io/language-server-protocol/][home]]
[2026-05-22 Fri 22:14] -- [[https://microsoft.github.io/language-server-protocol/specifications/specification-current][spec]]
:END:
#+begin_quote
A Language Server is meant to provide the language-specific smarts and
communicate with development tools over a protocol that enables
inter-process communication.

The idea behind the Language Server Protocol (LSP) is to standardize
the protocol for how such servers and development tools
communicate. This way, a single Language Server can be re-used in
multiple development tools, which in turn can support multiple
languages with minimal effort.
#+end_quote
* Debug Adapter Protocol
:PROPERTIES:
:ID:       3409e652-a0f2-4d03-9eeb-3206db3881bf
:CREATED:  <2026-06-05 Fri 17:37>
:END:
:EDGES:
[2026-06-05 Fri 17:37] -- [[https://microsoft.github.io/debug-adapter-protocol/][home]]
:END:
#+begin_quote
The idea behind the Debug Adapter Protocol (DAP) is to abstract the
way how the debugging support of development tools communicates with
debuggers or runtimes into a protocol. Since it is unrealistic to
assume that existing debuggers or runtimes adopt this protocol any
time soon, we rather assume that an intermediary component - a so
called Debug Adapter - adapts an existing debugger or runtime to the
Debug Adapter Protocol.

The Debug Adapter Protocol makes it possible to implement a generic
debugger for a development tool that can communicate with different
debuggers via Debug Adapters. And Debug Adapters can be re-used across
multiple development tools which significantly reduces the effort to
support a new debugger in different tools.
#+end_quote
