#+title: Forth
#+setupfile: ../../clean.theme
* Forth
:PROPERTIES:
:ID:       ffb8be57-d874-4540-9fe0-9efea6559185
:CREATED:  <2025-01-18 Sat 20:44>
:END:
:EDGES:
[2025-02-13 Thu 22:33] -- [[https://www.forth.com/][forth.com]]
[2025-03-09 Sun 20:54] -- [[https://raw.githubusercontent.com/nornagon/jonesforth/master/jonesforth.S][jonesforth.S]]
[2025-03-09 Sun 20:55] -- [[https://github.com/c2d7fa/jonasforth][c2d7fa/jonasforth: Forth interpreter written in bare-metal assembly running on UEFI (unfinished)]]
[2025-08-10 Sun 18:52] -- [[https://forth-standard.org/][Forth]]
:END:
- [2023-07-04 Tue]
  Factor is a cool concatenative lang but unfortunately the C interface
  (vm/master.h) no longer exists on the master branch.
- [[https://www.pbm.com/~lindahl/real.programmers.html][Real Programmers Don't Use Pascal]]
- [[https://piembsystech.com/assembly-and-machine-code-interfacing-in-forth-programming/][Assembly and Machine Code Interfacing in Forth Programming - PiEmbSysTech]]
- [[https://forth-standard.org/standard/testsuite][Annex F: Test Suite]]
  - test harness: http://www.forth200x.org/tests/ttester.fs
  - tests [[https://github.com/gerryjackson/forth2012-test-suite/][gerryjackson/forth2012-test-suite: Test programs for Forth 2012 and ANS Forth]]
:notes:
_implementation/_
- data stack - one-cell wide
- control-flow stack
- return stack - one or more cells
  - rules:
    #+begin_quote
    A program shall not access values on the return stack (using R@,
    R>, 2R@, 2R> or NR>) that it did not place there using >R, 2>R or
    N>R;

    A program shall not access from within a do-loop values placed on
    the return stack before the loop was entered;

    All values placed on the return stack within a do-loop shall be
    removed before I, J, LOOP, +LOOP, UNLOOP, or LEAVE is executed;

    All values placed on the return stack within a definition shall be
    removed before the definition is terminated or before EXIT is
    executed.
    #+end_quote

    #+begin_quote
    Forth words are organized into a structure called the
    dictionary. While the form of this structure is not specified by
    the standard, it can be described as consisting of three logical
    parts: a name space, a code space, and a data space. The logical
    separation of these parts does not require their physical
    separation.

    A program shall not fetch from or store into locations outside
    data space. An ambiguous condition exists if a program addresses
    name space or code spac
    #+end_quote
    
    names = 1-31 chars

    #+begin_quote
    The relationship between code space and data space is
    implementation dependent.


    Data space is the only logical area of the dictionary for which
    standard words are provided to allocate and access regions of
    memory. These regions are: contiguous regions, variables,
    text-literal regions, input buffers, and other transient regions,
    each of which is described in the following sections. A program
    may read from or write into these regions unless otherwise
    specified.
    #+end_quote

  - text-interpreter (repl) = 3.4

  - syntax
  #+begin_quote
  Forth has a simple, operator-ordered syntax. The phrase A B C
  returns values as if A were executed first, then B and finally
  C. Words that cause deviations from this linear flow of control are
  called control-flow words. Combinations of control-flow words whose
  stack effects are compatible form control-flow structures. Examples
  of typical use are given for each control-flow word in Annex A.

  Forth syntax is extensible; for example, new control-flow words can
  be defined in terms of existing ones. This standard does not require
  a syntax or program-construct checker.
  #+end_quote
:end:
** gforth
:PROPERTIES:
:ID:       c8359e6e-401b-4c7a-915f-98dc2759c995
:CREATED:  <2025-03-03 Mon 20:04>
:END:
:EDGES:
[2025-03-03 Mon 20:04] -- [[https://www.gnu.org/software/gforth/][Gforth - GNU Project - Free Software Foundation.]]
[2025-03-03 Mon 20:05] -- [[info:gforth][info]]
:END:
** avrforth
:PROPERTIES:
:ID:       8263ab5f-ced9-4bc6-b22c-2d1f319394ee
:CREATED:  <2025-08-08 Fri 21:38>
:END:
:EDGES:
[2025-08-08 Fri 21:38] -- [[http://krue.net/avrforth/][krüe :: avrforth]]
[2025-08-08 Fri 22:04] -> [[id:ec0316f3-db1a-4bcd-966c-2ac0bb3458f0][AVR]]
[2025-08-17 Sun 21:19] -> [[id:75819bf7-326d-49e1-8a4b-b93e1336b7db][avr-libc]]
:END:
- [[https://github.com/kristianlm/avr-emacs][kristianlm/avr-emacs: A proof of concept text editor from scratch on a breadboard using ATmega328 and avrforth]]
#+begin_quote
- overview
avrforth is a 16-bit subroutine threaded forth kernel for atmel's avr
series of microcontrollers. Current development is done for the
at90can128 (my cansynth board, to be exact), but it will run on most
any mega device with minimal adjustments.

avrforth borrows some ideas from Terry Loveall's 4word. It is a
colorless colorforth. The interpreter only interprets. Words must be
compiled explicitly using the ] operator. Numeric input is handled by
$, which parses the next word as a hexidecimal number.

avrforth uses null-terminated strings internally against tradition. I
may switch to counted strings if they prove easier to deal with.

avrforth supports using the entire 128k instruction address space of
the atmega128 and at90can128 for code.

avrforth has an interactive interpreter. It interprets input from the
uart and compiles directly to flash. avrforth does not require
separate memory to store program tokens.

avrforth has an integrated assembler. Assembly code words can be added
without recompiling the kernel.

avrforth is public domain.

- requirements
You need a host forth system to assemble avrforth. Development is done
with gforth. You also need a utility to program the flash and a
terminal program to communicate with the kernel through the avr's
uart. I use avrdude and picocom for those tasks.
#+end_quote
- [[https://dercuano.github.io/notes/forth-assembling.html][Forth assembling ⁑ Dercuano]]
** flashforth
:PROPERTIES:
:ID:       3f65cfc7-f3b0-4b50-b20a-d775936ad08f
:CREATED:  <2025-08-08 Fri 21:39>
:END:
:EDGES:
[2025-08-08 Fri 21:39] -- [[https://www.flashforth.com/][FlashForth]]
[2025-08-17 Sun 21:19] -> [[id:75819bf7-326d-49e1-8a4b-b93e1336b7db][avr-libc]]
:END:

** colorforth
:PROPERTIES:
:ID:       2a285bbe-715d-49a5-8fcb-df9921c3352b
:CREATED:  <2025-08-08 Fri 21:40>
:END:
:EDGES:
[2025-08-08 Fri 21:40] -- [[https://colorforth.github.io/][Chuck Moore's colorForth, OKAD and S40 Forth Multicomputer chip]]
:END:
** Books
:PROPERTIES:
:ID:       35de6467-e9fc-49f4-b46b-0e05029f9f48
:CREATED:  <2025-02-13 Thu 22:32>
:END:
:EDGES:
[2025-02-13 Thu 22:33] -- [[https://vfxforth.com/arena/ProgramForth.pdf][Programming Forth]]
:END:
* Factor
:PROPERTIES:
:CREATED:  <2025-01-18 Sat 20:44>
:ID:       b0f61b51-fbd8-4b45-a8cd-0a2e08864fed
:END:
:EDGES:
[2025-02-13 Thu 22:34] -- [[https://factorcode.org/][Factor programming language]]
:END:

* Joy
:PROPERTIES:
:CREATED:  <2025-01-18 Sat 20:44>
:ID:       39af0f8f-aff7-40f3-a139-e1338a6bb966
:END:
:EDGES:
[2025-02-06 Thu 18:55] -- [[https://hypercubed.github.io/joy/html/j02maf.html][Mathematical foundations of Joy]]
:END:
